name: <CDN> Publish API Document
on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOC_DIR: "./doc/typedoc"
      DOC_DEPLOY_DIR: "./_deploy/doc/"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run:  git fetch --prune --unshallow
      - name: Get deploy version
        run: |
          NEXT_VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo ${NEXT_VERSION}
          echo "::set-output name=next_version::${NEXT_VERSION}"
        id: get_version
        shell: bash
        working-directory: ${{ env.CORE_PACKAGE_DIR }}
      - name: Setup
        run: yarn install
      - name: Generate documents
        run: yarn doc
      - name: Copy core built files to dist directory
        run: |
          mkdir -p ${{ env.DOC_DEPLOY_DIR }}/v${{ steps.get_version.outputs.next_version }}
          cp -r ${{ env.DOC_DIR }}/* ${{ env.DOC_DEPLOY_DIR }}/v${{ steps.get_version.outputs.next_version }}/
        shell: bash
      - name: Upload API documents files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ${{ env.DOC_DEPLOY_DIR }}
          destination: inou-pro-released/doc/api
          credentials: ${{ secrets.STORE_CREDENTIALS }}
          parent: false

