name: <NPM pre-release> Publish node packages

on:
  release:
    types: [prereleased]

jobs:
  npm:
    runs-on: ubuntu-latest
    env:
      CORE_PACKAGE_DIR: "./packages/mapray"
      UI_PACKAGE_DIR: "./packages/ui"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org
          scope: '@mapray'
      - run:  git fetch --prune --unshallow
      - name: Get current version
        run: |
          TAG_NAME=$(echo ${{ github.ref }} |  grep -o -E "(dev|alpha|beta|rc)")
          echo "::set-output name=tag_name::${TAG_NAME}"
        id: get_version
        shell: bash
      - name: Setup
        run: yarn install
      - name: Build maprayJS
        run: yarn build
      - name: Packing core package
        run: yarn pack
        working-directory: ${{ env.CORE_PACKAGE_DIR }}
      - name: Packing ui package
        run: yarn pack
        working-directory: ${{ env.UI_PACKAGE_DIR }}
      - name: Publish core to npm packages
        run: find ./ -name "*.tgz" -type f | xargs npm publish --tag ${{ steps.get_version.outputs.tag_name }}
        working-directory: ${{ env.CORE_PACKAGE_DIR }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish ui to Github packages
        run: find ./ -name "*.tgz" -type f | xargs npm publish --tag ${{ steps.get_version.outputs.tag_name }}
        working-directory: ${{ env.UI_PACKAGE_DIR }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

